### ISSUE TITLE
invalid api

### ISSUE THREAD

**Issue by suriyaJaay** [petehouston/simple-newsletter#1]
am getting the following line from console.

server listening at: 3000
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/do
promises.html
New subscription { asd:hi.jayasurya@gmail.com } has been saved successfully!
{ status: 'error',
  code: -1,
  name: 'Invalid_Key',
  message: 'Invalid API key' }

**find the below image** after signing in it show like below.

![stay tune](https://cloud.githubusercontent.com/assets/19813670/20096125/71b79206-a5ce-11e6-89ac-a3f8a5a49f34.PNG)

what is next step?

**Comment by petehouston** [comment]
Use promise http://mongoosejs.com/docs/promises.html

Mandrill service had been shutdown for a year.

This repo is a fun demo project, use and fix at your own will.
